# Generated by Django 3.0.2 on 2020-01-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20200128_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.Price'),
        ),
    ]
